### ISSUE TITLE
[QUESTION]drawable 추가할때 질문!!

### ISSUE THREAD

**Issue by clode-wf** [SujungVillage/SujungVillage-User-Android#13]
다들 drawable 파일 추가할 때, 버전을 그냥 drawable로 했어 아니면 drawable-v24로 했어?? 둘 차이 검색했는데 정확히 이해가 안가서.. 일단은 그냥 drawable 버전으로 올리고 작업할게!

**Comment by b1urrrr** [comment]
나는 별 생각 없이 drawable에 추가하고 있었는데 검색해보니까 되게 심오하다... drawable-v21에는 벡터 이미지를 넣고 drawable에는 비트맵 이미지를 추가하라는 것 같아! 비트맵이랑 벡터가 뭔지 몰라서 얘네도 한번 찾아봤어

- https://points.tistory.com/84
> 이러한 문제 해결을 위해 drawable-v21 폴더에는 벡터 이미지 파일들을 추가하고, 그 이전 버전의 안드로이드(4.4 킷캣, API v20)를 위해서 drawable 폴더에 비트맵 이미지를 추가하도록 변경된 것이죠.

- https://imweb.me/faq?mode=view&category=29&category2=33&idx=71515
> 비트맵 이미지는 점(픽셀)들의 조합으로 그려지는 이미지 표현 방식으로 크기를 늘리거나 줄이면 원본 이미지에 손상이 간다.
> 벡터 이미지는 점과 점을 연결해 수학적 원리로 그림을 그려 표현하는 방식으로 크기를 늘리고 줄여도 손상되지 않는 장점이 있지만, 사진과 같은 복잡한 그림을 표현하려면 컴퓨터에 엄청난 부담을 주곤 했기에 웹에서는 잘 사용되지 않았다.

얘네 구분해서 넣어야 하나? (구분은 어떻게 해야하지)

**Comment by clode-wf** [comment]
음.. 읽어보니까 drawable-v24에 넣는게 더 좋긴 한 것 같은데 사실 별 차이 없을 것 같아서 우선 다들 drawable에 한 것 같으니까 그냥 drawable로 통일하자!
