### ISSUE TITLE
[QUESTION] 버튼 색이 바뀌지 않음

### ISSUE THREAD

**Issue by flora7883** [SujungVillage/SujungVillage-User-Android#36]
버튼에 백그라운드 적용해서 색깔을 바꾸려는데 테두리 둥글기는 잘 적용되는데 색만 바뀌지 않는 상황. 다른 엑티비티에서는 잘 바꼈는데 comm_write에서만 바뀌지 않는 기묘한 상황..
`<Button
                android:id="@+id/button2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@drawable/style_comm_write_submit_border"
                android:text="등록"
                android:textColor="@color/white"
                android:textSize="16dp"
                android:layout_gravity="center"
                />`

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:top="0dp">
        <shape android:shape="rectangle">
            <solid android:color="@color/primary" />
            <corners android:radius="30dp"/>
        </shape>
    </item>
</layer-list>`

**Comment by b1urrrr** [comment]
한번 버튼 backgroundTint 속성을 primary로 설정해봐! 버튼은 background로 색이 안 변했던 것 같기도 해 🤔

**Comment by flora7883** [comment]
> 한번 버튼 backgroundTint 속성을 primary로 설정해봐! 버튼은 background로 색이 안 변했던 것 같기도 해 🤔

해봤는데 반영이 안되네..
진짜 이상한건 RollCall에서도 똑같이 했는데 그건 잘 반영 됐어..
아니다 그건 textWiew로 했엇네..!

**Comment by b1urrrr** [comment]
왜 그러지...? push 해놓으면 한번 확인해볼게! 어느 브렌치야?

**Comment by flora7883** [comment]
> 왜 그러지...? push 해놓으면 한번 확인해볼게! 어느 브렌치야?

해결 방법 찾았어!  < Button>말고 <androidx.appcompat.widget.AppCompatButton>으로 하면 drawable 적용 잘 돼!
