### ISSUE TITLE
[QUESTION] 체크박스 아이콘 크기 조절

### ISSUE THREAD

**Issue by b1urrrr** [SujungVillage/SujungVillage-User-Android#56]
체크박스 아이콘 크기 조절을 어떻게 하는지 모르겠습니다… 외박신청에 사용 중이야!

**Comment by clode-wf** [comment]
나는 그거 글씨 지우고 체크박스만 따로 생성해서 크기 조절한다음에 글씨는 따로 넣었어!! 채연이가 모른다는 부분이 이게 맞는진 모르겠지만..!

**Comment by b1urrrr** [comment]
> 나는 그거 글씨 지우고 체크박스만 따로 생성해서 크기 조절한다음에 글씨는 따로 넣었어!! 채연이가 모른다는 부분이 이게 맞는진 모르겠지만..!

나도 그냥 따로 만들어야겠다 고마워!
