### ISSUE TITLE
[QUESTION] 점호 위치 주소 반환이 미국으로 되는 이유

### ISSUE THREAD

**Issue by b1urrrr** [SujungVillage/SujungVillage-User-Android#71]
지금 점호할 때 위치 새로고침하면 미국 본사 주소가 나오던데
실제 휴대폰 위치의 주소가 반환되려면 어떻게 해야 하는거야?

**Comment by clode-wf** [comment]
https://rina214.tistory.com/24
이거 중간부터 따라하면 될듯!!

**Comment by b1urrrr** [comment]
고마워 👍
